name: Build & Release (rootless .deb)

on:
  push:
    tags: ['v*']   # push a tag like v1.0.0 to build a release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps (brew)
        run: |
          brew update
          brew install dpkg ldid
          
      - name: Set up THEOS
        run: |
          git clone --depth=1 https://github.com/theos/theos.git $HOME/theos
          sudo mkdir -p /opt
          sudo ln -s $HOME/theos /opt/theos
          # Point Theos at the iOS SDK on the macOS runner
          SDK_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
          mkdir -p "$HOME/theos/sdks"
          ln -s "$SDK_PATH" "$HOME/theos/sdks/iPhoneOS.sdk"
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          # sanity checks
          ls -la $HOME/theos/bin
          test -f $HOME/theos/bin/dm.pl || (echo "dm.pl missing" && exit 1)

      - name: Build & Package (rootless)
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          # if your Makefile hard-codes /opt/theos, the symlink above covers it
          make clean package THEOS_PACKAGE_SCHEME=rootless
          ls -la packages
