name: Build & Release (rootless .deb)

on:
  push:
    tags: ['v*']   # push a tag like v1.0.0 to build a release
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install deps (brew)
        run: |
          brew update
          brew install dpkg ldid
          
     - name: Set up THEOS
        run: |
          # Clone Theos WITH submodules
          git clone --depth=1 --recurse-submodules https://github.com/theos/theos.git $HOME/theos
          # (belt-and-braces in case recurse-submodules ever misses anything)
          git -C $HOME/theos submodule update --init --recursive
      
          # Make it available at /opt/theos for projects that expect that
          sudo mkdir -p /opt
          sudo ln -s $HOME/theos /opt/theos || true
      
          # Point Theos at the iOS SDK already on the macOS runner
          SDK_PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
          mkdir -p "$HOME/theos/sdks"
          ln -sf "$SDK_PATH" "$HOME/theos/sdks/iPhoneOS.sdk"
      
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
      
          # sanity check: dm.pl should now resolve
          ls -la $HOME/theos/bin
          test -f $HOME/theos/bin/dm.pl || (echo "dm.pl still missing" && exit 1)
